import Head from 'next/head'
import Header from './components/Header';
import Sectionhero from './components/Sectionhero';
// import './../styles/Bootstrap.module.css'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Header /> */}
      <h1>Lilo Next JS</h1>
      <main>
        <Sectionhero />
      </main>
    </div>
  )
}
